kanban termcap foo

diff --git a/roles/0x09_util/files/kanban b/roles/0x09_util/files/kanban
--- a/roles/0x09_util/files/kanban
+++ b/roles/0x09_util/files/kanban
@@ -1,21 +1,25 @@
-#!/bin/bash
+#!/usr/bin/env bash
 #
 # commandline asciii kanban board for minimalist productivity bash hackers (csv-based)
 #
 # Usage:
 #
+#   kanban init                             # initialize kanban in current directory
 #   kanban add                              # add item interactive (adviced)
-#   kanban show [status] ....               # show ascii kanban board [with status]
+#   kanban show [dir with .kanban]          # show global [or nested] ascii kanbanboard
 #   kanban <id>                             # edit or update item
 #   kanban <id> <status>                    # update status of todo id (uses $EDITOR as preferred editor)
 #   kanban <status> .....                   # list only todo items with this status(es)
 #   kanban list                             # list all todos (heavy)
 #   kanban tags                             # list all submitted tags
 #   kanban add <status> <tag> <description> # add item (use quoted strings for args)
-#   kanban stats <status|tag> [<str>]       # generates stats
+#   kanban stats status [tag]
+#   kanban stats tag
+#   kanban stats history
+#   kanban csv                              # edit raw csv
 #
-#   NOTE #1: statuses can be managed in ~/.kanban/config
-#   NOTE #2: the database csv can be found in ~/.kanban/db.csv
+#   NOTE #1: statuses can be managed in ~/.kanban/.kanban.conf
+#   NOTE #2: the database csv can be found in ~/.kanban/.kanban.csv
 #
 # Examples:
 #
@@ -23,19 +27,24 @@
 #   kanban TODO DOING HOLD
 #   kanban stats status projectX
 #   kanban stats tag projectX
+#   # notekeeping by entering a filename as description:
+#   echo hello > note.txt && kanban add DOING note.txt
+#   # store in github repo
+#   git clone https://../foo.git && cd foo.git && kanban init && git add .kanban
 #
 # Environment:
 #
-#   You can switch context (e.g. work vs home vs project x ) like so:
+#   X=120 kanban ....         # set max line-width to 120
+#   NOCOLOR=1 kanban ....     # disable colors
+#   PLAIN=1 kanban ...        # plaintext, disable utf8 chars
 #
-#   KANBANFILE=~/.kanban.foo.csv kanban show
-#   KANBANFILE=~/.kanban.foo.csv KANBANCONF=~/.kanban.foo.conf kanban show
+# Tips:
 #
-#   KANBANFILE env-var is not needed when a .kanban.csv file is present in the current working dir
-#   KANBANCONF is created automatically if not found
+#   * <current_dir>/.kanban or ~/.kanban dir is checked for configuration / data
+#   * put .kanban directories in project-dirs
+#   * entering an existing text-filename as description enables note-keeping
 #
 # Copyright (C) 2015, Leon van Kammen / Coder of Salvation
-# Shortcuts 2017, sjas
 #
 #  This program is free software: you can redistribute it and/or modify
 #  it under the terms of the GNU Affero General Public License as
@@ -49,9 +58,16 @@
 #
 #  You should have received a copy of the GNU Affero General Public License
 #  along with this program.  If not, see <http://www.gnu.org/licenses/>.
+deps="tput column pr gawk"
+for dep in $deps; do which $dep &>/dev/null || { echo "$dep-cmd not installed..aborting (maybe install coreutils util-linux pkgs?)"; exit 1; }; done
 BOX=(┌ ─ ┐ └ ┘ │ ┤ ┴ ┬ ├ ┼)
 BAR=(▁ ▂ ▃ ▄ ▅ ▆ ▆ ▇ ▇ '█' '█')
-TMP=~/.kanban.tmp
+COL0="\033[0m"
+COL1="\033[37;1m"
+COL2="\033[91;1m"
+COL3="\033[91;5m"
+TMP=$(mktemp -t kanban.XXXXXXXX)
+[[ ! -n $TERM ]] && TERM=vt100
 locale | grep -q "UTF-8" && UTF8=1
 X=$(tput cols)    # get size of terminal window
 #Y=$(tput lines)   #
@@ -63,37 +79,43 @@ if [[ -z $KANBANFILE ]]; then
 fi
 [[ ! -f $KANBANFILE ]] && echo "status,tag,description,history,date" > "$KANBANFILE"
 
-## config_example="# kanban config file
-##
-## # kanban config file
-## statuses=('BACKLOG' 'HOLD' 'DOING' 'CODE' 'DONE')
-##
-## # maximum amount of todos within status (triggers warning when exceeds)
-## declare -A maximum_todo
-## maximum_todo['HOLD']=5
-## maximum_todo['DOING']=4
-## maximum_todo['CODE']=3
-## "
 
 config_example="# kanban config file
+statuses=('TODO' 'HOLD' 'DOING' 'DONE' 'NOTES' 'BACKLOG')
 
-# kanban config file
-statuses=('BL' 'TD' 'DO' 'HK' 'EX')  ## stick with uppercase letters
+XSMALL=119                           # show small kanban for terminalwidth < 119 chars
+SMALLSCREEN=('DOING' 'TODO' 'HOLD')  # define simplified kanban board statuses
 
 # maximum amount of todos within status (triggers warning when exceeds)
-declare -A maximum_todo
-maximum_todo['TD']=5
-maximum_todo['DO']=4
-maximum_todo['HK']=3
+declare -a maximum_todo
+maximum_todo[HOLD]=10
+maximum_todo[DOING]=5
 "
 
 # usage: fb put <x> <y> <string>
 put() { printf "\x1B[%s;%sf%s %s" "$2" "$1" "$3" "$4"; }
 
 strtoline(){ for((i=0;i<${#1};i++)); do printf "%s" "$2"; done; }
+=======
+strtoline() {
+    str="$1"
+    char="$2"
+    i=0
+    len=${#str}
 
-draw_line(){
-  for((i=0;i<$1;i++)); do printf "-"; done
+    while [ "$i" -lt "$len" ]; do
+        printf "%s" "$char"
+        i=$((i + 1))
+    done
+}
+>>>>>>> 182bf01 (kanban termcap foo)
+
+draw_line() {
+    i=0
+    while [ "$i" -lt "$1" ]; do
+        printf "-"
+        i=$((i + 1))
+    done
 }
 
 # usage: fb box <x> <y> <width> <height>
@@ -110,10 +132,8 @@ createconfig(){
   echo "$config_example" > "$KANBANCONF"
 }
 
-t(){
-  shift
-  tags "$@"
-}
+init(){ createconfig "$(pwd)"; }
+
 tags(){
   awk -F',' '{ print $2 }' "$KANBANFILE" | sed 's/,.*//g;s/"//g' | tail -n+2 | sort | uniq | tr '\n' ' '
 }
@@ -147,14 +167,15 @@ st(){
   [[ -z $1 ]] && exit 1
   stats "$@"
 }
+
 stats(){
   [[ -z $1 ]] && exit 1
   create_index
   field=$1; shift; tags="$*"
   greppattern="(${tags// /\|})"
-  [[ "$field" == "status" ]]  && field=2 || [[ "$field" == "s" ]] && field=2
-  [[ "$field" == "tag" ]]     && field=3 || [[ "$field" == "t" ]]  && field=3
-  [[ "$field" == "history" ]] && field=5 || [[ "$field" == "h" ]]  && field=5
+  [[ "$field" == "status" ]]  && field=2
+  [[ "$field" == "tag" ]]     && field=3
+  [[ "$field" == "history" ]] && field=5
   [[ -n $2 ]] && WIDTH=$2   || WIDTH=20;
   [[ -n $3 ]] && PADDING=$3 || PADDING=20;
   {
@@ -171,9 +192,6 @@ init(){
   #trap "tput cnorm -- normal" 0 1 5    # reset terminal colors to normal
 }
 
-l(){
-  list "$@"
-}
 list(){
   tags="$*"
   greppattern="(${tags// /\|})"
@@ -210,13 +228,25 @@ columnize(){
 }
 
 lines(){
+  echo -e "$COL1"
   if [[ -n $UTF8 ]]; then
-    cat - | sed 's/| /├╴/g;s/~/━/g;s/|+/┕━/g;s/|_/│ /g' # nice utf8 lines
-  else cat - | sed 's/~/-/g;s/|+/|/g;s/|+/| /g;s/|_/| /g'; fi
+    cat | sed 's/| /│ /g;s/\.~/┌/g;s/~\./──┐/g;s///g;s/~/─/g;s/|\./└/g;s/|/│/g' # nice utf9 lines
+  else
+    cat | sed 's/~/-/g;s/|+/|/g;';
+  fi | colorize 3
+}
+
+colorize(){
+  cat | awk '{
+    a = gensub(/#([a-zA-Z0-9_\.-]+) /,"'$COL1'&'$COL0'","g")
+    a = gensub(/\*([a-zA-Z0-9_\.-]+)\*/,"'$COL3'&'$COL0'","g",a)
+    if( NR == '$1' ){ printf "'$COL0'"; }
+    print a
+  }'
 }
 
 align(){
-  cat - | awk '{ for(i=3;i<=NF;i++){ $2=$2" "$i } printf "%-5s %s\n", $1,$2 ; }'
+  cat | awk '{ for(i=3;i<=NF;i++){ $2=$2" "$i } printf "%-5s %s\n", $1,$2 ; }'
 }
 
 s(){
@@ -226,16 +256,27 @@ sh(){
 	show "$@"
 }
 show(){
+  [[ -n $1 ]] && { cd $1; echo "[kanban] showing nested kanban '$1'"; $0 show; exit 0; }
   [[ ! -f "$KANBANFILE" ]] && touch "$KANBANFILE"
   create_index
   if [[ -n $1 ]]; then
     statuses=(); for status in "$@"; do statuses+=("$status"); done
   fi
-  clear;  {
+  {
     echo "$1"
     if [[ -n $1 ]]; then cat $TMP.index | grep "$1"; else cat $TMP.index; fi
-  } | columnize | more
+  } | columnize
+  [[ -n $SMALLSCREEN ]] && echo -e "    ${COL1}(${COL0} small terminal detected, hiding certain columns ${COL1})"
   echo ""
+  ls */.kanban/.kanban.conf 2>/dev/null | awk '{
+    if( !START ){
+      print "kanbans: "
+      START=1
+    }
+    gsub("^./","",$0)
+    gsub("/.kanban.*","",$0)
+    print "   ├─ "$0
+  }'
 }
 
 get_current_date(){ date "+%Y-%m-%d@%H:%M"; }
@@ -263,6 +304,10 @@ update_item(){
   item="$(awk "{ if (NR==$1) print \$0 }" "$KANBANFILE" )"
   [[ ${#item} == 0 ]] && echo "item $1 not found" && exit 1
   status="$(echo "$item" | awk -F',' '{ print $1 }')"
+  file="$(echo "$item" | awk -F',' '{ print $3 }')"
+  file="${file//\"/}"
+  [[ -d $file/.kanban ]] && { show $file; return; }
+  [[ -f $file ]] && ${EDITOR} "$file"
   echo '#
 # STATUSES ARE: '"${statuses[*]}"'
 #
@@ -285,9 +330,8 @@ printcsv(){
 [[ ! -f $KANBANCONF ]] && mkdir -p ~/.kanban && { createconfig; }
 # shellcheck disable=SC1090
 . "$KANBANCONF"
-
 # execute main
-init
+_init
 
 if [[ -n "$1" ]]; then
 
@@ -301,4 +345,4 @@ if [[ -n "$1" ]]; then
     *)       "$@"
              ;;
   esac
-else grep -A29 "^# Usage:" "$0" | sed 's/^# //g'; fi
+else grep -A40 "^# Usage:" "$0" | sed 's/^# //g' | more ; fi
